highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://maxrojass.github.io/
author: Maximiliano Rojas-Delgado

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Maximiliano Rojas-Delgado's Resume
name: Maximiliano Rojas-Delgado
email: maxrojasdel94@gmail.com
email_full: mailto:maxrojasdel94@gmail.com
website: http://maxrojass.github.io/
website_full: http://maxrojass.github.io/
github: maxrojass
twitter: twitter
tel: +351 936 497 668
tel_full: tel:+351936497668
google_maps: ''
address:
  street: #
  postcode: #
  city: Porto
  country: Portugal
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
